import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { AlertTriangle } from "lucide-react";

interface AgeVerificationGateProps {
  children: React.ReactNode;
}

export function AgeVerificationGate({ children }: AgeVerificationGateProps) {
  const [isVerified, setIsVerified] = useState<boolean | null>(null);

  useEffect(() => {
    const verified = localStorage.getItem("ageVerified");
    setIsVerified(verified === "true");
  }, []);

  const handleConfirm = () => {
    localStorage.setItem("ageVerified", "true");
    setIsVerified(true);
  };

  const handleDeny = () => {
    window.location.href = "https://www.google.com";
  };

  if (isVerified === null) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!isVerified) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center space-y-4">
            <div className="mx-auto w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
              <AlertTriangle className="w-8 h-8 text-primary" />
            </div>
            <CardTitle className="text-2xl font-bold">Age Verification Required</CardTitle>
            <CardDescription className="text-base">
              Vivid Vixen is an adult content generation platform. You must be 18 years or older to access this site.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="rounded-lg bg-muted p-4 space-y-2 text-sm">
              <p className="font-semibold">Content Warning:</p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                <li>This site contains explicit adult content (NSFW)</li>
                <li>All content is generated by AI and is not real</li>
                <li>You must be 18+ to view and generate content</li>
                <li>By continuing, you agree to our Terms of Service</li>
              </ul>
            </div>
            
            <div className="space-y-3 pt-2">
              <Button 
                data-testid="button-confirm-age"
                onClick={handleConfirm} 
                className="w-full"
                size="lg"
              >
                I am 18 or older - Enter Site
              </Button>
              <Button 
                data-testid="button-deny-age"
                onClick={handleDeny} 
                variant="outline" 
                className="w-full"
                size="lg"
              >
                I am under 18 - Exit
              </Button>
            </div>

            <p className="text-xs text-center text-muted-foreground pt-4">
              By clicking "I am 18 or older", you confirm that you are of legal age to view adult content in your jurisdiction and agree to our Terms of Service and Content Policy.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return <>{children}</>;
}
